import { Amplify } from 'aws-amplify'

// Generated by `npx ampx sandbox` (local dev) or the Amplify Hosting build
// (`ampx pipeline-deploy`, see amplify.yml). Not committed — run the sandbox
// once locally before `npm run web`/`npm start` so this file exists.
import outputs from '../../amplify_outputs.json'

Amplify.configure(outputs)
