const { defineConfig } = require('eslint/config')
const expoConfig = require('eslint-config-expo/flat')

module.exports = defineConfig([
  { ignores: ['dist/**', '.amplify/**'] },
  ...expoConfig,
  {
    rules: {
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z_]' }],
      // Generated by `ampx sandbox`; absent until the backend is deployed.
      'import/no-unresolved': ['error', { ignore: ['^\\$amplify/'] }],
    },
  },
])
